### ISSUE TITLE
Оборачивание шаблонов в <script> попахивает бекбоном

### ISSUE THREAD

**Issue by jt3k** [monkberry/standalone#1]
В век es6, бабеля и вебпака в примерах думаю правильней юзить стринг-темплейт-треугольные кавычки ```

К сожалению в этом случае мы теряем возможность подсвечивать код внутри кавычек.

**Comment by jt3k** [comment]
Хм. не дочитал  ридмишку до конца, но осуждаю. :)
Всо ок. там перечислены всевозможные способы использования

**Comment by antonmedv** [comment]
Угу, slandalone для использования на jsfiddle в основном.
